# Generated by Django 4.1.7 on 2024-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_img', models.URLField()),
                ('game_url', models.URLField(unique=True)),
                ('game_rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('game_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('game_date', models.DateField()),
                ('game_publisher', models.CharField(max_length=100)),
                ('game_category', models.ManyToManyField(related_name='games', to='gameprofile.category')),
                ('game_platform', models.ManyToManyField(related_name='games', to='gameprofile.platform')),
            ],
        ),
    ]
