# Generated by Django 4.1.3 on 2024-02-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='game_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='game_platform',
            new_name='platform',
        ),
    ]
