# Generated by Django 4.1.3 on 2024-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameprofile', '0002_rename_game_category_profile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
