# Generated by Django 4.1.3 on 2024-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameprofile', '0003_alter_profile_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(to='gameprofile.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.ManyToManyField(to='gameprofile.platform'),
        ),
    ]
