# Generated by Django 4.1.3 on 2024-02-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameprofile', '0004_alter_profile_category_alter_profile_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(related_name='category', to='gameprofile.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.ManyToManyField(related_name='platform', to='gameprofile.platform'),
        ),
    ]
