# Generated by Django 4.1.7 on 2024-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameprofile", "0005_alter_profile_category_alter_profile_platform"),
        ("shoppingcart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="games",
            field=models.ManyToManyField(
                through="shoppingcart.orderItem", to="gameprofile.profile"
            ),
        ),
    ]
